name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Criando um input para efeito de estudo'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Testando o output'
    value: ${{ steps.install.outputs.cache }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      id: checkout

    - name: Cache dependencies
      id: install
      run: echo "::set-output name=cache::${{ inputs.caching }}"
      shell: bash
