name: 'Get & Cache Dependencies'
description : 'Get the dependencies (via npm) and cache them'
inputs: 
 caching:
 description: 'Criando um input para efeito de estudo'
 required: false
 default: 'true'
 
runs: 
  using: 'composite'
  steps:
    - name : Cache dependencies
      uses: actions/checkout@v3
      id: cache
